version: '3.3'
services:
  db:
    image: postgres:9.5.6-alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pyjobs
      POSTGRES_PASSWORD: pyjobs
      POSTGRES_DB: pyjobs
    ports:
      - '5432:5432'

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env


